# Generated by Django 3.0.3 on 2020-02-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_server_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disk',
            name='server',
        ),
        migrations.AlterField(
            model_name='server',
            name='last_date',
            field=models.DateField(blank=True, null=True, verbose_name='最近汇报时间'),
        ),
        migrations.DeleteModel(
            name='AssetsRecord',
        ),
        migrations.DeleteModel(
            name='Disk',
        ),
    ]
